/**
 * Campaign Model
 *
 * Represents a WhatsApp marketing campaign that groups multiple bulk messaging runs.
 * A campaign tracks aggregate statistics across all its bulk messagings and provides
 * high-level organization for WhatsApp broadcast activities.
 *
 * Use Cases:
 * - Seasonal promotions (e.g., "Diwali 2024 Discount Campaign")
 * - Product launches (e.g., "New Feature Announcement")
 * - User engagement drives (e.g., "Profile Completion Drive")
 * - Renewal reminders (e.g., "Q1 2024 Renewal Campaign")
 *
 * Key Features:
 * - Groups related bulk messaging activities
 * - Tracks aggregate stats (sent, delivered, read, failed)
 * - Supports budget tracking and cost management
 * - Tag-based organization for reporting
 *
 * Database Collection: BM-Campaigns
 */

import mongoose, { Schema, Document } from "mongoose";

/**
 * Campaign Status Lifecycle:
 * - draft: Campaign is being set up, not yet active
 * - active: Campaign is live and accepting new bulk messagings
 * - paused: Temporarily halted, can be resumed
 * - completed: All planned messaging completed
 * - archived: Historical record, no longer in use
 */
export type CampaignStatus = "draft" | "active" | "paused" | "completed" | "archived";

/**
 * Campaign Statistics
 * These numbers are aggregate sums from all bulk messagings in this campaign
 */
export interface CampaignStats {
  /** Total number of bulk messaging runs created under this campaign */
  totalBulkMessagings: number;

  /** Total messages queued across all bulk messagings */
  totalMessages: number;

  /** Successfully sent to Meta WhatsApp API */
  totalSent: number;

  /** Delivered to recipient's WhatsApp */
  totalDelivered: number;

  /** Opened/read by recipient */
  totalRead: number;

  /** Failed to send or deliver */
  totalFailed: number;
}

/**
 * Campaign Document Interface
 * Extends Mongoose Document with campaign-specific fields
 */
export interface CampaignDocument extends Document {
  /** Human-readable campaign name (e.g., "Black Friday 2024") */
  name: string;

  /** Optional description explaining campaign purpose */
  description?: string;

  /** Campaign type/category - can be extended based on business needs */
  type: string;

  /** Current lifecycle status */
  status: CampaignStatus;

  /**
   * Default template to use for this campaign's bulk messagings
   * Reference to WhatsAppTemplate model
   * TODO: CHANGE THIS - Update ref to match your template model name
   */
  defaultTemplateId?: mongoose.Types.ObjectId;

  /** Aggregate statistics across all bulk messagings */
  stats: CampaignStats;

  /**
   * User who created this campaign
   * TODO: CHANGE THIS - Update ref to match your user/admin model
   * Currently references "CompanyMaster" from BusinessMeet
   */
  createdBy?: mongoose.Types.ObjectId;

  /** Tags for filtering and organization (e.g., ["promotion", "renewal"]) */
  tags: string[];

  /** Total cost incurred across all bulk messagings in this campaign */
  totalCost: number;

  /** Optional budget limit to prevent overspend */
  budgetLimit?: number;

  /** Auto-generated by timestamps: true */
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Campaign Schema Definition
 */
const CampaignSchema = new Schema<CampaignDocument>(
  {
    name: {
      type: String,
      required: true,
      trim: true,
      maxlength: 200,
    },
    description: {
      type: String,
      trim: true,
      default: "",
      maxlength: 1000,
    },
    type: {
      type: String,
      default: "general",
      trim: true,
    },
    status: {
      type: String,
      enum: ["draft", "active", "paused", "completed", "archived"],
      default: "draft",
      index: true,
    },
    defaultTemplateId: {
      type: Schema.Types.ObjectId,
      ref: "WhatsAppTemplate", // TODO: CHANGE THIS - Update to your template model
      default: null,
    },
    stats: {
      totalBulkMessagings: { type: Number, default: 0, min: 0 },
      totalMessages: { type: Number, default: 0, min: 0 },
      totalSent: { type: Number, default: 0, min: 0 },
      totalDelivered: { type: Number, default: 0, min: 0 },
      totalRead: { type: Number, default: 0, min: 0 },
      totalFailed: { type: Number, default: 0, min: 0 },
    },
    createdBy: {
      type: Schema.Types.ObjectId,
      ref: "User", // TODO: CHANGE THIS - Update if your user model has different name
    },
    tags: [{ type: String, trim: true, maxlength: 50 }],
    totalCost: { type: Number, default: 0, min: 0 },
    budgetLimit: { type: Number, default: null, min: 0 },
  },
  {
    timestamps: true,
    collection: "BM-Campaigns",
  }
);

/**
 * Indexes for query optimization
 * - createdAt: Sorting campaigns by creation date (newest first)
 * - createdBy: Finding all campaigns created by a specific user
 */
CampaignSchema.index({ createdAt: -1 });
CampaignSchema.index({ createdBy: 1 });

/**
 * Compound index for common query patterns
 * Example: "Show me all active campaigns, newest first"
 */
CampaignSchema.index({ status: 1, createdAt: -1 });

/**
 * Export the Campaign model
 * Uses Mongoose's model registry to prevent duplicate model errors
 */
export const CampaignModel =
  mongoose.models.Campaign ??
  mongoose.model<CampaignDocument>("Campaign", CampaignSchema);
